// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// is_big_endian
bool is_big_endian();
RcppExport SEXP _qs_is_big_endian() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(is_big_endian());
    return rcpp_result_gen;
END_RCPP
}
// c_qsave
void c_qsave(SEXP x, std::string file, std::string preset, std::string algorithm, int compress_level, int shuffle_control, bool check_hash, int nthreads);
RcppExport SEXP _qs_c_qsave(SEXP xSEXP, SEXP fileSEXP, SEXP presetSEXP, SEXP algorithmSEXP, SEXP compress_levelSEXP, SEXP shuffle_controlSEXP, SEXP check_hashSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type preset(presetSEXP);
    Rcpp::traits::input_parameter< std::string >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< int >::type compress_level(compress_levelSEXP);
    Rcpp::traits::input_parameter< int >::type shuffle_control(shuffle_controlSEXP);
    Rcpp::traits::input_parameter< bool >::type check_hash(check_hashSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    c_qsave(x, file, preset, algorithm, compress_level, shuffle_control, check_hash, nthreads);
    return R_NilValue;
END_RCPP
}
// c_qread
SEXP c_qread(std::string file, bool use_alt_rep, bool strict, int nthreads);
RcppExport SEXP _qs_c_qread(SEXP fileSEXP, SEXP use_alt_repSEXP, SEXP strictSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< bool >::type use_alt_rep(use_alt_repSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(c_qread(file, use_alt_rep, strict, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// c_qdump
RObject c_qdump(std::string file);
RcppExport SEXP _qs_c_qdump(SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    rcpp_result_gen = Rcpp::wrap(c_qdump(file));
    return rcpp_result_gen;
END_RCPP
}
// randomStrings
std::vector<std::string> randomStrings(int N, int string_size);
RcppExport SEXP _qs_randomStrings(SEXP NSEXP, SEXP string_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type string_size(string_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(randomStrings(N, string_size));
    return rcpp_result_gen;
END_RCPP
}
// zstd_compress_bound
int zstd_compress_bound(int size);
RcppExport SEXP _qs_zstd_compress_bound(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(zstd_compress_bound(size));
    return rcpp_result_gen;
END_RCPP
}
// lz4_compress_bound
int lz4_compress_bound(int size);
RcppExport SEXP _qs_lz4_compress_bound(SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lz4_compress_bound(size));
    return rcpp_result_gen;
END_RCPP
}
// zstd_compress_raw
std::vector<unsigned char> zstd_compress_raw(RawVector x, int compress_level);
RcppExport SEXP _qs_zstd_compress_raw(SEXP xSEXP, SEXP compress_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type compress_level(compress_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(zstd_compress_raw(x, compress_level));
    return rcpp_result_gen;
END_RCPP
}
// zstd_decompress_raw
RawVector zstd_decompress_raw(RawVector x);
RcppExport SEXP _qs_zstd_decompress_raw(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(zstd_decompress_raw(x));
    return rcpp_result_gen;
END_RCPP
}
// lz4_compress_raw
std::vector<unsigned char> lz4_compress_raw(RawVector x, int compress_level);
RcppExport SEXP _qs_lz4_compress_raw(SEXP xSEXP, SEXP compress_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type compress_level(compress_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(lz4_compress_raw(x, compress_level));
    return rcpp_result_gen;
END_RCPP
}
// lz4_decompress_raw
std::vector<unsigned char> lz4_decompress_raw(RawVector x);
RcppExport SEXP _qs_lz4_decompress_raw(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lz4_decompress_raw(x));
    return rcpp_result_gen;
END_RCPP
}
// blosc_shuffle_raw
std::vector<unsigned char> blosc_shuffle_raw(std::vector<uint8_t> x, int bytesofsize);
RcppExport SEXP _qs_blosc_shuffle_raw(SEXP xSEXP, SEXP bytesofsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<uint8_t> >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type bytesofsize(bytesofsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(blosc_shuffle_raw(x, bytesofsize));
    return rcpp_result_gen;
END_RCPP
}
// blosc_unshuffle_raw
std::vector<unsigned char> blosc_unshuffle_raw(std::vector<uint8_t> x, int bytesofsize);
RcppExport SEXP _qs_blosc_unshuffle_raw(SEXP xSEXP, SEXP bytesofsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<uint8_t> >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type bytesofsize(bytesofsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(blosc_unshuffle_raw(x, bytesofsize));
    return rcpp_result_gen;
END_RCPP
}
// convertToAlt
SEXP convertToAlt(CharacterVector x);
RcppExport SEXP _qs_convertToAlt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(convertToAlt(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qs_is_big_endian", (DL_FUNC) &_qs_is_big_endian, 0},
    {"_qs_c_qsave", (DL_FUNC) &_qs_c_qsave, 8},
    {"_qs_c_qread", (DL_FUNC) &_qs_c_qread, 4},
    {"_qs_c_qdump", (DL_FUNC) &_qs_c_qdump, 1},
    {"_qs_randomStrings", (DL_FUNC) &_qs_randomStrings, 2},
    {"_qs_zstd_compress_bound", (DL_FUNC) &_qs_zstd_compress_bound, 1},
    {"_qs_lz4_compress_bound", (DL_FUNC) &_qs_lz4_compress_bound, 1},
    {"_qs_zstd_compress_raw", (DL_FUNC) &_qs_zstd_compress_raw, 2},
    {"_qs_zstd_decompress_raw", (DL_FUNC) &_qs_zstd_decompress_raw, 1},
    {"_qs_lz4_compress_raw", (DL_FUNC) &_qs_lz4_compress_raw, 2},
    {"_qs_lz4_decompress_raw", (DL_FUNC) &_qs_lz4_decompress_raw, 1},
    {"_qs_blosc_shuffle_raw", (DL_FUNC) &_qs_blosc_shuffle_raw, 2},
    {"_qs_blosc_unshuffle_raw", (DL_FUNC) &_qs_blosc_unshuffle_raw, 2},
    {"_qs_convertToAlt", (DL_FUNC) &_qs_convertToAlt, 1},
    {NULL, NULL, 0}
};

void init_stdvec_double(DllInfo* dll);
RcppExport void R_init_qs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    init_stdvec_double(dll);
}
