# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_big_endian <- function() {
    .Call(`_qs_is_big_endian`)
}

c_qsave <- function(x, file, preset = "balanced", algorithm = "lz4", compress_level = 1L, shuffle_control = 15L, nthreads = 4L) {
    invisible(.Call(`_qs_c_qsave`, x, file, preset, algorithm, compress_level, shuffle_control, nthreads))
}

c_qread <- function(file, use_alt_rep = FALSE) {
    .Call(`_qs_c_qread`, file, use_alt_rep)
}

c_qdump <- function(file) {
    .Call(`_qs_c_qdump`, file)
}

randomStrings <- function(N, string_size = 50L) {
    .Call(`_qs_randomStrings`, N, string_size)
}

zstd_compress_bound <- function(size) {
    .Call(`_qs_zstd_compress_bound`, size)
}

lz4_compress_bound <- function(size) {
    .Call(`_qs_lz4_compress_bound`, size)
}

zstd_compress_raw <- function(x, compress_level) {
    .Call(`_qs_zstd_compress_raw`, x, compress_level)
}

zstd_decompress_raw <- function(x) {
    .Call(`_qs_zstd_decompress_raw`, x)
}

lz4_compress_raw <- function(x, compress_level) {
    .Call(`_qs_lz4_compress_raw`, x, compress_level)
}

lz4_decompress_raw <- function(x) {
    .Call(`_qs_lz4_decompress_raw`, x)
}

blosc_shuffle_raw <- function(x, bytesofsize) {
    .Call(`_qs_blosc_shuffle_raw`, x, bytesofsize)
}

blosc_unshuffle_raw <- function(x, bytesofsize) {
    .Call(`_qs_blosc_unshuffle_raw`, x, bytesofsize)
}

convertToAlt <- function(x) {
    .Call(`_qs_convertToAlt`, x)
}

