# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_SIMD <- function() {
    .Call(`_qs_check_SIMD`)
}

zstd_compress_bound <- function(size) {
    .Call(`_qs_zstd_compress_bound`, size)
}

lz4_compress_bound <- function(size) {
    .Call(`_qs_lz4_compress_bound`, size)
}

zstd_compress_raw <- function(x, compress_level) {
    .Call(`_qs_zstd_compress_raw`, x, compress_level)
}

zstd_decompress_raw <- function(x) {
    .Call(`_qs_zstd_decompress_raw`, x)
}

lz4_compress_raw <- function(x, compress_level) {
    .Call(`_qs_lz4_compress_raw`, x, compress_level)
}

lz4_decompress_raw <- function(x) {
    .Call(`_qs_lz4_decompress_raw`, x)
}

blosc_shuffle_raw <- function(x, bytesofsize) {
    .Call(`_qs_blosc_shuffle_raw`, x, bytesofsize)
}

blosc_unshuffle_raw <- function(x, bytesofsize) {
    .Call(`_qs_blosc_unshuffle_raw`, x, bytesofsize)
}

xxhash_raw <- function(x) {
    .Call(`_qs_xxhash_raw`, x)
}

base85_encode <- function(rawdata) {
    .Call(`_qs_base85_encode`, rawdata)
}

base85_decode <- function(encoded_string) {
    .Call(`_qs_base85_decode`, encoded_string)
}

c_base91_encode <- function(rawdata) {
    .Call(`_qs_c_base91_encode`, rawdata)
}

c_base91_decode <- function(encoded_string) {
    .Call(`_qs_c_base91_decode`, encoded_string)
}

is_big_endian <- function() {
    .Call(`_qs_is_big_endian`)
}

qsave <- function(x, file, preset = "high", algorithm = "zstd", compress_level = 4L, shuffle_control = 15L, check_hash = TRUE, nthreads = 1L) {
    invisible(.Call(`_qs_qsave`, x, file, preset, algorithm, compress_level, shuffle_control, check_hash, nthreads))
}

c_qsave <- function(x, file, preset, algorithm, compress_level, shuffle_control, check_hash, nthreads) {
    .Call(`_qs_c_qsave`, x, file, preset, algorithm, compress_level, shuffle_control, check_hash, nthreads)
}

qsave_fd <- function(x, fd, preset = "high", algorithm = "zstd", compress_level = 4L, shuffle_control = 15L, check_hash = TRUE) {
    invisible(.Call(`_qs_qsave_fd`, x, fd, preset, algorithm, compress_level, shuffle_control, check_hash))
}

qsave_handle <- function(x, handle, preset = "high", algorithm = "zstd", compress_level = 4L, shuffle_control = 15L, check_hash = TRUE) {
    invisible(.Call(`_qs_qsave_handle`, x, handle, preset, algorithm, compress_level, shuffle_control, check_hash))
}

qserialize <- function(x, preset = "high", algorithm = "zstd", compress_level = 4L, shuffle_control = 15L, check_hash = TRUE) {
    .Call(`_qs_qserialize`, x, preset, algorithm, compress_level, shuffle_control, check_hash)
}

c_qserialize <- function(x, preset, algorithm, compress_level, shuffle_control, check_hash) {
    .Call(`_qs_c_qserialize`, x, preset, algorithm, compress_level, shuffle_control, check_hash)
}

qread <- function(file, use_alt_rep = FALSE, strict = FALSE, nthreads = 1L) {
    .Call(`_qs_qread`, file, use_alt_rep, strict, nthreads)
}

c_qattributes <- function(file, use_alt_rep = FALSE, strict = FALSE, nthreads = 1L) {
    .Call(`_qs_c_qattributes`, file, use_alt_rep, strict, nthreads)
}

c_qread <- function(file, use_alt_rep, strict, nthreads) {
    .Call(`_qs_c_qread`, file, use_alt_rep, strict, nthreads)
}

qread_fd <- function(fd, use_alt_rep = FALSE, strict = FALSE) {
    .Call(`_qs_qread_fd`, fd, use_alt_rep, strict)
}

qread_handle <- function(handle, use_alt_rep = FALSE, strict = FALSE) {
    .Call(`_qs_qread_handle`, handle, use_alt_rep, strict)
}

qread_ptr <- function(pointer, length, use_alt_rep = FALSE, strict = FALSE) {
    .Call(`_qs_qread_ptr`, pointer, length, use_alt_rep, strict)
}

qdeserialize <- function(x, use_alt_rep = FALSE, strict = FALSE) {
    .Call(`_qs_qdeserialize`, x, use_alt_rep, strict)
}

c_qdeserialize <- function(x, use_alt_rep, strict) {
    .Call(`_qs_c_qdeserialize`, x, use_alt_rep, strict)
}

qdump <- function(file) {
    .Call(`_qs_qdump`, file)
}

openFd <- function(file, mode) {
    .Call(`_qs_openFd`, file, mode)
}

readFdDirect <- function(fd, n_bytes) {
    .Call(`_qs_readFdDirect`, fd, n_bytes)
}

closeFd <- function(fd) {
    .Call(`_qs_closeFd`, fd)
}

openMmap <- function(fd, length) {
    .Call(`_qs_openMmap`, fd, length)
}

closeMmap <- function(map, length) {
    .Call(`_qs_closeMmap`, map, length)
}

openHandle <- function(file, mode) {
    .Call(`_qs_openHandle`, file, mode)
}

closeHandle <- function(handle) {
    .Call(`_qs_closeHandle`, handle)
}

openWinFileMapping <- function(handle, length) {
    .Call(`_qs_openWinFileMapping`, handle, length)
}

openWinMapView <- function(handle, length) {
    .Call(`_qs_openWinMapView`, handle, length)
}

closeWinMapView <- function(pointer) {
    .Call(`_qs_closeWinMapView`, pointer)
}

register_altrep_class <- function(classname, pkgname) {
    invisible(.Call(`_qs_register_altrep_class`, classname, pkgname))
}

unregister_altrep_class <- function(classname, pkgname) {
    invisible(.Call(`_qs_unregister_altrep_class`, classname, pkgname))
}

get_altrep_class_info <- function(obj) {
    .Call(`_qs_get_altrep_class_info`, obj)
}

set_trust_promises <- function(value) {
    .Call(`_qs_set_trust_promises`, value)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_qs_RcppExport_registerCCallable`)
})
